### Important Note: example configurations are nested inside fictitious example namespaces in order to avoid naming collisions
###                 When reusing example configs, take care to remove the example namespace in property paths

## 1. Multi-tenant setup with explicit database_urls

[example1.tenants.crocoder]
  subdomain = "crocoder"
  name = "crocoder"
  database_url = "sqlite://crocoder.db"

[example1.tenants.acme]
  subdomain = "acme"
  name = "acme"
  database_url = "sqlite://acme.db"

## 2. Multi-tenant setup with templating. 

[example2]
  tenant_database_url_template = "sqlite://%s.db" # %s is tenants[key in tenants][database_name] || [key in tenants]

[example2.tenants.crocoder]
  name = "Crocoder"
  # database_url == sqlite://acme.db

[example2.tenants.acme]
  name = "ACME"
  database_name = "acme_local"
  # database_url == sqlite://acme_local.db

## 3. Single-tenant setup. For use with localhost

[example3.tenants.acme]
  subdomain = "acme"
  name = "acme"
  database_url = "sqlite://acme.db"

## 4. Super database setup.

[example4]
  super_database_url = "sqlite://super.db"
  tenant_database_url_template = "%s" # %s is super_database.tenants[db_url]
