// Code generated by templ - DO NOT EDIT.

// templ: version: 0.2.476
package admin_template

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"

type CrawlInstanceInfoProps struct {
}
