
--
-- LibSQL SQL Schema dump automatic generated by geni
--

CREATE TABLE schema_migrations (id VARCHAR(255) NOT NULL PRIMARY KEY)
CREATE TABLE repos (id INTEGER PRIMARY KEY AUTOINCREMENT, organization TEXT NOT NULL, repository TEXT NOT NULL, db_url TEXT NOT NULL, __created_at INTEGER DEFAULT ((strftime ('%s', 'now') || substr (printf ('%.3f', julianday ('now') - julianday ('1970-01-01')), 4, 3)) * 1), __updated_at INTEGER DEFAULT ((strftime ('%s', 'now') || substr (printf ('%.3f', julianday ('now') - julianday ('1970-01-01')), 4, 3)) * 1), UNIQUE (organization, repository))
CREATE TABLE sqlite_sequence(name,seq)
CREATE INDEX idx_org_repo_repos ON repos (organization, repository)
CREATE TRIGGER repos_update_updated_at AFTER UPDATE ON repos BEGIN
UPDATE repos SET __updated_at = ((strftime ('%s', 'now') || substr (printf ('%.3f', julianday ('now') - julianday ('1970-01-01')), 4, 3)) * 1) WHERE id = old.id;
END