tenant_database_url_template = "sqlite://%s.db" # %s is tenants[key in tenants][database_name] || [key in tenants]

[tenants.crocoder]
  subdomain = "crocoder" # optional
  name = "crocoder" # optional
  # database_url is evaluated as "sqlite://crocoder.db"

[tenants.dxta]
  database_name = "dxta-dev"
  # database_url is evaluated as "sqlite://dxta-dev.db"

[tenants.acme]
  database_url = "libsql://john-cena" # optional; overrides template usage
