
--
-- LibSQL SQL Schema dump automatic generated by geni
--

CREATE TABLE schema_migrations (id VARCHAR(255) NOT NULL PRIMARY KEY);
CREATE TABLE "tenants" ("id" INTEGER PRIMARY KEY NOT NULL, "organization_id" TEXT NOT NULL UNIQUE, "db_url" TEXT NOT NULL, deleted_at DATETIME DEFAULT NULL, "created_at" DATETIME NOT NULL DEFAULT (datetime ('now')), "updated_at" DATETIME NOT NULL DEFAULT (datetime ('now')), name TEXT NOT NULL DEFAULT '', domain TEXT NOT NULL DEFAULT '');
CREATE TRIGGER "tenants_updated_at" AFTER UPDATE ON "tenants" FOR EACH ROW BEGIN
UPDATE "tenants" SET updated_at = datetime ('now') WHERE id = OLD.id;
END;