name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions: read-all


env:
  TEST_TAG: user/app:test

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup bun
        uses: oven-sh/setup-bun@f4d14e03ff726c06358e5557344e1da148b56cf7 # v1.2.2
        with:
          bun-version: 1.1.13

      - name: Setup go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: 1.22.2

      - name: Setup bun cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        id: bun-cache
        with:
          path: |
            ./node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('./bun.lockb') }}

      - name: bun install
        if: steps.bun-cache.outputs.cache-hit != 'true'
        run: |
          bun i

      - name: Setup generate cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        id: generate-cache
        with:
          path: |
            ./public/style.css
            ./internal/template/**/*_templ.go
          key: ${{ runner.os }}-generate-${{ hashFiles('./internal/template/**/*.templ') }}

      - name: Generate
        if: steps.generate-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p bin/
          go install github.com/a-h/templ/cmd/templ@v0.2.663
          templ generate
          ./node_modules/.bin/tailwindcss -i ./style.css -o ./public/style.css

  test:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: 1.22.2

      - name: Restore generate cache
        uses: actions/cache/restore@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: |
            ./public/style.css
            ./internal/template/**/*_templ.go
          key: ${{ runner.os }}-generate-${{ hashFiles('./internal/template/**/*.templ') }}

      - name: Test
        run: |
          go test -v ./...

  build:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: 1.22.2

      - name: Restore generate cache
        uses: actions/cache/restore@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: |
            ./public/style.css
            ./internal/template/**/*_templ.go
          key: ${{ runner.os }}-generate-${{ hashFiles('./internal/template/**/*.templ') }}

      - name: Dry Build Web
        run: |
          go build -o ./tmp/main ./cmd/web/main.go

      - name: Dry Build Admin
        run: |
          go build -o ./tmp/admin ./cmd/admin/main.go

  docker:
    needs: [test, setup, build]
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0

      - name: Dry Build Web
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5.4.0
        with:
          context: .
          load: true
          file: ./Dockerfile
          tags: ${{ env.TEST_TAG }}

      - name: Dry Build Admin
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5.4.0
        with:
          context: .
          load: true
          file: ./admin.dockerfile
          tags: ${{ env.TEST_TAG }}
