name: CI

on: [pull_request]

env:
  TEST_TAG: dxta/app
  GO_VERSION: 1.21.5
  BUN_VERSION: 1.0.21

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup bun cache
        uses: actions/cache@v3
        id: bun-cache
        with:
          path: |
            ./node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('./bun.lockb') }}

      - name: bun install
        if: steps.bun-cache.outputs.cache-hit != 'true'
        run: |
          bun i

      - name: Setup generate cache
        uses: actions/cache@v3
        id: generate-cache
        with:
          path: |
            ./public/style.css
            ./internals/templates/**/*_templ.go
          key: ${{ runner.os }}-generate-${{ hashFiles('./internals/templates/**/*.templ') }}

      - name: Generate
        if: steps.generate-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p bin/
          go install github.com/a-h/templ/cmd/templ@latest
          templ generate
          ./node_modules/.bin/tailwindcss -i ./style.css -o ./public/style.css

  test:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Restore generate cache
        uses: actions/cache/restore@v3
        with:
          path: |
            ./public/style.css
            ./internals/templates/**/*_templ.go
          key: ${{ runner.os }}-generate-${{ hashFiles('./internals/templates/**/*.templ') }}

      - name: Test
        run: |
          go test -v ./...

  build:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Restore generate cache
        uses: actions/cache/restore@v3
        with:
          path: |
            ./public/style.css
            ./internals/templates/**/*_templ.go
          key: ${{ runner.os }}-generate-${{ hashFiles('./internals/templates/**/*.templ') }}

      - name: Dry Build
        run: |
          go build -o ./tmp/main ./cmd/web/main.go

  docker-e2e:
    needs: [test, setup, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Dry build
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          push: false
          tags: ${{ env.TEST_TAG }}:${{ github.sha }}

      - name: Run Docker Image
        run: docker run -p 3000:3000 ${{ env.TEST_TAG }}:${{ github.sha }}

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - name: Restore bun cache
        uses: actions/cache@v3
        id: bun-cache
        with:
          path: |
            ./node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('./bun.lockb') }}

      - name: Run Playwright Tests
        run: npx playwright test

      - name: Upload Test Artifact (if tests fail)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-screenshots
          path: test-results/


