name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions: read-all


env:
  TEST_TAG: user/app:test

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.26

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Setup bun cache
        uses: actions/cache@v3
        id: bun-cache
        with:
          path: |
            ./node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('./bun.lockb') }}

      - name: bun install
        if: steps.bun-cache.outputs.cache-hit != 'true'
        run: |
          bun i

      - name: Setup generate cache
        uses: actions/cache@v3
        id: generate-cache
        with:
          path: |
            ./public/style.css
            ./internal/template/**/*_templ.go
          key: ${{ runner.os }}-generate-${{ hashFiles('./internal/template/**/*.templ') }}

      - name: Generate
        if: steps.generate-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p bin/
          go install github.com/a-h/templ/cmd/templ@latest
          templ generate
          ./node_modules/.bin/tailwindcss -i ./style.css -o ./public/style.css

  test:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Restore generate cache
        uses: actions/cache/restore@v3
        with:
          path: |
            ./public/style.css
            ./internal/template/**/*_templ.go
          key: ${{ runner.os }}-generate-${{ hashFiles('./internal/template/**/*.templ') }}

      - name: Test
        run: |
          go test -v ./...

  build:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Restore generate cache
        uses: actions/cache/restore@v3
        with:
          path: |
            ./public/style.css
            ./internal/template/**/*_templ.go
          key: ${{ runner.os }}-generate-${{ hashFiles('./internal/template/**/*.templ') }}

      - name: Dry Build
        run: |
          go build -o ./tmp/main ./cmd/web/main.go

  docker:
    needs: [test, setup, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Dry build
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}
